bin/build-packages: add message if upload of package failed

diff --git a/bin/build-packages b/bin/build-packages
--- a/bin/build-packages
+++ b/bin/build-packages
@@ -460,6 +460,7 @@ while [ "${count}" -ne 0 ]; do
             "${master_build_server_user}@${master_build_server}" \
             'return-assignment' "${package}" "${git_revision}" "${mod_git_revision}" "${repository}" 'ERROR' < \
             'build-logs.gz.tar'; do
+            >&2 echo 'There was an error during the upload of the package, I will try again.'
             wait_some_time 15
           done
         fi
