add shared lock for sanity-check

diff --git a/bin/sanity-check b/bin/sanity-check
--- a/bin/sanity-check
+++ b/bin/sanity-check
@@ -66,6 +66,12 @@ do
   shift
 done
 
+exec 9> "${sanity_check_lock_file}"
+if ! flock -n 9; then
+  >&2 echo 'Sanity check skipped, cannot acquire lock.'
+  exit 11
+fi
+
 finish() {
   if ${web}; then
     {
diff --git a/bin/show-dependencies b/bin/show-dependencies
--- a/bin/show-dependencies
+++ b/bin/show-dependencies
@@ -107,7 +107,13 @@ fi
 
 exec 9> "${work_dir}/${0##*/}.lock"
 if ! flock -n 9; then
-  echo 'Cannot get lock.'
+  >&2 echo 'Cannot get show-dependencies lock.'
+  exit
+fi
+
+exec 8> "${sanity_check_lock_file}"
+if ! flock -s -n 8; then
+  >&2 echo 'Cannot get sanity-check lock.'
   exit
 fi
 
